[messenger]
host = "localhost"
port = 23561
ip_whitelist = ['127.0.0.1']
songlist = [
    113847973189770, # 这首港风粤语味太浓啦！「拍硬档」
    114274349355828, # 🌈 𝑶𝒗𝒆𝒓 𝒕𝒉𝒆 𝑹𝒂𝒊𝒏𝒃𝒐𝒘✨
    114459334938781, # 【完整版】好可怕 好可怕 好可怕 好可怕 好可怕…
    114550435223167, # 《高达00》Trust you~听完的在座都互相理解了
    114725790684003, # 夏夜的风有你，就是我还在等待的爱
    114759697439768, # 【粤语版】萌虎来也！食通万物 修心修身
    114737668952235, # 不如笑着唱『 莫愁乡 』
    114392477799407, # “时间啊 停下吧 想比你多活一秒…”『 青春にして已む 』
    # 114358705198016, # 「DM2025 DAY1」舞台阵容+演出时段【电则市场DizzyMart2025】
    # 113990596368214, # 美少女甜又苦涩的爱恋！《吉祥不如意》【虚拟UP新春会单品】
    # 113956286959799, # 用6种方言送你《春意红包》！虚拟歌势给你拜个晚年啦！
    113939929112566, # 我不会是最后一个唱这首歌的吧
    113929661453425, # 🌘在 宇 宙 邊 緣 睡 著 了💤
    113900234216503, # 今年过年就听我这首！《迎春花》可爱又喜庆！
    113854751184781, # 唱得最快的一集！《绝区零》耀嘉音丨乐园游梦记丨翻唱
    113786467915645, # 哭着唱『 𝑪𝒓𝒚 𝑭𝒐𝒓 𝑴𝒆 』
    # 113735750390143, # 【萤光宇宙·闪耀之夜】早稻叽 特邀嘉宾访谈
    113673255261597, # ♥全网最雌小鬼♥ぬぬぬぬぬぬぬぬぬぬぬぬぬぬぬぬ￤みむかｩわナイストライ￤早稻叽￤
    113469697433588, # 极致高音女声粤语「这样很好」丨《双城之战2》主题曲
    113385240795178, # ⚡粤语也能不乱不破！⚡
    113338298212034, # 《未尽之歌》缀好听的粤语版！
    113310800350928, # 【V你而唱】早稻叽-《坦诉》| 决赛嘉宾【歌切纯享版】
    113298905242112, # ⚡让 我 们 唱 粤 语⚡
    112998274304685, # 【早稻叽×Tacitly】梦幻共演！ちゅ、多様性。| 啾、多样性。
    112998240749750, # 【早稻叽×Tacitly】初次合作！君の知らない物語 | 你不知道的故事
    1756026921,      # 慵懒地边扭边唱💗Say So💗将熟未熟，惹人心动！【中国绊爱x早稻叽】
    1705761283,      # 唱点柔的！《Viva La Vida 1999》
    1055983638,      # 我唱这歌是真帅吧『 Waking of a World 』
    1005133708,      # 我们会找到极光的！《Aurora》碧蓝航线七周年
    1105070758,      # 【早稻叽x真白花音x折原露露】我们是大家推的孩子哦！💖サインはB(暗号是B)／B小町💖
    1404506685,      # 粤语版 「希望有羽毛和翅膀」 高音超流畅~【早稻叽】
    1654439448,      # 《稻香》还记你说家是唯一的城堡 随着稻香河流继续奔跑~
    1804382184,      # 『 忍者 』你可曾听过又奶又帅的rap？
    # 1703919810,      # 菜叽组合儿歌二连唱，小心别被可爱晕啦！【冰火歌会】
    # 1903744390,      # 知 道 我 要 唱 什 么 了 吧 ？(肛门收缩术)
    1053565278,      # 帅死你的粤语rap！《Everywhere We Go》完整版！
    # 1453250969,      # 最对味的Everywhere We Go，准备好包袱和我走路了吗！
    1152849364,      # ⚡我 在 5:20 睡 觉 13:14 准 时 起⚡
    1602912382,      # 『 爱在西元前 』我从3700年前就开始爱你了
    1752072723,      # 头文字D：听完开86都稳了不少！
    1651840659,      # 『 灯光 』“若没有你我根本就没办法发光”
    1901350149,      # 《白色羽毛》周杰伦还写过这么好听的歌啊！
    1550956901,      # 第一次听到这首歌我就沦陷了
    1400295427,      # 八珍玉食【2024拜年纪单品】
    1150072141,      # “邀请你和我一起做一个甜涩之梦…❤️”【早稻叽原创曲】
    1350163760,      # ✨『 不眠之夜 』我将用粤语和高音征服你！
    624116561,       # 啊叽姑娘唱『 阿楚姑娘 』【直播现场版丨早稻叽】
    283758802,       # 超可爱的粤语版《可爱补习法》还不快来听！？
    241027715,       # 『 暗号 』“别吵，这里很好听！”【直播现场版丨早稻叽】
    750497747,       # 超好听的女声粤语版『 圣诞星 』来啦~【早稻叽】
    495216034,       # 最让你放松的女声版『 圣诞星 』⭐祝你圣诞快乐~【早稻叽】
    537471515,       # 虚拟黄绮珊的『 拆穿 』直播现场版丨早稻叽
    964731801,       # 『 我的美丽』直播现场版丨早稻叽
    408511903,       # 没有人能拒绝我唱粤语小甜歌！💖『 非常完美 』
    961829912,       # 【冰火歌会】经典粤语《李香兰》丨早稻叽
    661292962,       # 【早稻叽x梦音】～爱着每一天和你～『drop pop candy』
    275393260,       # 用最绝望的嘶吼唱了「文学少年的忧郁」【早稻叽丨初音生日快乐】
    915137892,       # 你的爱马也可以是小恶魔！❤️
    317809266,       # 神级催泪现场，用最大声的呐喊唱出了「在没能成为未来的夜里」
    702699590,       # 因为我是最强偶像！「アイドル」3D唱跳舞台现场【早稻叽】
    273331143,       # 『 笼 』倾尽感情的高音…！
    997710823,       # 【3D现场】梦与叶樱【早稻叽】
    742478924,       # 【早稻叽】雅典娜蹦跶指南【原创丨专辑先行曲】
    869729951,       # 充满力量的唱了《我们都拥有海洋》你的未来一定闪闪发光！
    398666651,       # “今夜想与你手指纠缠…❤️”『 夢をみせて 』
    313601946,       # 唱了一首很好听的粤语歌，送给你~（分分钟需要你）
    400661063,       # 男女恶魔对唱《不得不》【早稻叽×凛 | 冰火歌会】
    655165601,       # ⚠️强 风 大 秃 头⚠️
    570043879,       # 经典粤语备胎曲《七友》女声深情演绎
    312176102,       # 『 Stay Gold 』我的声音会戳中你的内心吗？“因为我最喜欢你啦”
    909462353,       # 『 铃芽 』空灵粤语版，这首歌太适合粤语了！！
    696022429,       # 『 𝑳𝒐𝒗𝒆 𝒔𝒄𝒂𝒓 』女声抒情Rap💧
    310691375,       # 《甩葱歌》但是呆呆的唱OAO
    780746461,       # 我爱你❤️不知道就唱给你听！(# ` n´ )
    267960806,       # 听我一记可爱暴击！洗脑原创《见习恶魔》「MuseDash」Buro角色曲【早稻叽】
    865284841,       # “希望你今后的每一次笑，都是真心的！”『 再见深海 』
    352525827,       # 『 乌梅子酱 』甜甜的，听完就像吃了乌梅子酱~
    267170658,       # 「早稻叽原创」是否缺少一个借口，邀请你一同甜蜜出走【秘宝旅人】
    736567874,       # ⚡️ 爱如火 ⚡️但是奶凶版
    436295057,       # 2023拜年纪『小孩小孩』女声版【早稻叽】
    650788159,       # 『 飞行艇 』燃死你的女声摇滚！
    608202799,       # 『 财神到 』粤语元气女声，今年过年就听我这首吧！
    265579997,       # 『 清平误 』柔美戏腔演唱
    820468563,       # 『糖不甩』惊艳冷门国风粤语翻唱！【早稻叽冰火3D舞台】
    990239673,       # 复古金曲对唱『突如其来的爱情』又甜又御！粤日双语风情演绎与你的爱情故事♥【中国绊爱x早稻叽】
    734940280,       # “这首歌就当我写给你的最后一首…”『 不要让我后悔 』
    222057238,       # 新年快乐！学了3天动画做的pv『 大吉 』
    263578766,       # “我需要你的时候，为什么你不在啊！骗子！”『 嘘つき 』
    690372030,       # 『 月光 』文艺复兴！你没听过的绝美女声…🌙
    987342743,       # 『 若把你 』绝美演唱，听到副歌，你会爱上我的！
    902053162,       # 2022最惊艳的英语歌『 Golden Hour 』女声版
    304420180,       # 温柔少女『晴天』我永远喜欢周杰伦！
    774303384,       # 深情的唱了温柔却冷门的歌，你愿意倾听吗？『 Promise with You 』
    689307780,       # 『 唯一 』我真的爱你，句句不轻易
    # 816663145,       # 不看必后悔的【早稻叽惊艳3D舞台现场】！
    473953333,       # 顶级现场合唱《甲铁城的卡巴内瑞》片尾曲 -『 Ninelie 』
    516147957,       # ⚠️危 险 派 对⚠️ 甜美酷妹顶级合唱【早稻叽×银杏Kyou】
    814697406,       # 最温柔的演唱…🌙『星尘中的维纳斯』
    216899235,       # 文艺复兴『 红线 』中文翻唱／早稻叽
    386843245,       # 喝醉后唱病娇歌能有多癫狂？
    771198434,       # 全网首发！粤语版《红颜如霜》女声翻唱
    771092579,       # 女声翻唱粤语金曲《喜欢你》广东人必点，回忆满满！【冰火现场】
    601104511,       # 忧郁旗袍少女版『 红颜如霜 』
    642553787,       # 激燃女版《追梦赤子心》向前跑！！年轻人！！
    299921015,       # 『 向着光 』爱会化作光芒，照耀悲伤的你／早稻叽三周年
    639656922,       # 『 万一对了呢 』你们都会成为想成为的人的
    427041801,       # 全网最甜日语版《爱你》连rap也甜到❤️里
    # 641901604,       # V 圈 王 心 凌 ❤️
    939279102,       # 『 下雨天 』开口便勾起你的回忆！
    854131020,       # ❤️神 圣 恶 魔 净 化 你❤️
    684050683,       # “我不想做太阳，我不想再逞强”
    683884812,       # 『 喜剧 』慵懒女声完整版《间谍过家家》ED／早稻叽
    553554892,       # 『 鱼仔 』献给奔波在人生路上的每个人【感谢70w关注】
    595910885,       # 『 雨爱 』“请给我爱上你的勇气吧”
    683254051,       # 『 轮到孔明来给你洗脑了 』❤️粤语可爱翻唱
    938162119,       # 直击灵魂治愈女声《me me she》欢迎RADWIMPS入驻B站！
    640449320,       # 【早稻叽】现场深情演唱！爆火网剧《开端》片尾曲《My only》【冰火歌会】
    895199036,       # 绝美高音《月兔回旋于空中》不要输给明天呐！
    467380192,       # 《彩虹》温柔少女翻唱❤️要天天开心鸭！
    509809454,       # 升4key超燃华丽高音⚠️鬼灭游郭篇op《残響散歌》
    979860639,       # 「悪魔の子-二重唱」“这世界无比残酷，但我却依然爱着你”【中国绊爱x早稻叽】
    809518936,       # 女备胎之歌《钟无艳》粤语深情翻唱！
    894406306,       # 《月牙湾》翻唱🌙听完你会爱上我的！
    339062145,       # 《霓 虹 甜 心》妩媚少女翻唱❤️
    296271486,       # 直播时竟然被要求唱B站《镇 站 之 宝》！
    296137458,       # “自从爱上你，我的人生因你乱了套”
    211236766,       # 2022拜年纪《新春小记》早稻叽单人版
    211129843,       # 新春小记【2022拜年纪单品】
    723350084,       # 【猛男必听】喝五斤奶粉后唱出来的JOJO！
    893315670,       # 《银河录》用我的歌声点燃银河系！
    593089067,       # 会触动你内心的呐喊《被生命所厌恶》吉他抒情版
    380303548,       # 【猛男必听】DIO当年就是听这首歌被萌死的
    210230205,       # 感冒了，随便飙一段高音
    592702931,       # 【早稻叽×花丸晴琉】随便随便随便【冰火歌合战sp】
    892514340,       # 用男女合唱来解锁『国王排名』OP《BOY》【早稻叽x凛】
    464944880,       # 「Rubia-二重唱」“这一次，我不会让你再孤单一人了！”【中国绊爱x早稻叽】（P2动态壁纸已更新）
    677282590,       # 【催泪预警】一首听完会让你想好好活着的歌…【早稻叽丨直播现场】
    422132431,       # 《海色》翻唱-祝自己生日快乐【早稻叽】
    506753993,       # 【早稻叽】来和恶魔一起唱《夏天的风》！
    891734261,       # 明日的夜空哨戒班-钢琴抒情版【早稻叽】
    # 378933573,       # 虚拟主播心得【合唱】少女，再生产！
    721474979,       # 《Oz.》国王排名ed翻唱-这首歌真的太好哭了…【早稻叽】
    890785005,       # 我只是第一次做人，不知道多疼也要忍…【早稻叽丨直播翻唱】
    720252754,       # 《STAY》第一次奶帅风唱英语歌！/早稻叽
    547254022,       # 【绯赤艾莉欧×早稻叽】东京夏日相会（七夕合唱❤️‬）
    759781165,       # 【早稻叽】夏日恶作剧/夏日イタズラ-原创曲首发❤️
    # 249466802,       # 【热爱105°C的你+追梦赤子心】早稻叽-冰火歌合战Ⅻ
    249189971,       # 【早稻叽】我的悲伤是水做的【直播剪辑】
    # 546190969,       # 【直播虚拟酱28】早稻叽真情流露献唱《银色飞行船》 七海《无垠梦海》诉说成长感受
    931125260,       # 女声日语版《热爱105°C的你》最甜日语填词❤️
]

[qmsg]
enabled = false
key = "60d3ffb38dff381c8178cfa75c7e8315"

[blrec]
url = "http://localhost:63151"
